### ISSUE TITLE
clj-tuple version conflict with other ztellman libraries

### ISSUE THREAD

**Issue by luxbock** [ztellman/vertigo#6]
Would it be possible to get a version bump that uses a newer version of clj-tuple? The renaming of `clj-tuple/tuple` to `clj-tuple/vector` is causing some problems for me in a project that uses your other libraries, which use the newer clj-tuple version.

**Comment by ztellman** [comment]
Hey, sorry for the late reply on this, I've been traveling.  I shortsightedly took out `tuple` from clj-tuple in 0.2.0, which caused unnecessary breakages.  If you target version 0.2.2, it has `tuple` as an alias for `vector`, which should make everything work again.  I'm going to do a pass on every project targeting 0.2.0 or 0.2.1 and upgrade, which should make everything work again, but you can solve it for yourself by explicitly adding 0.2.2 to your project.clj.
